# This Dockerfile is used to build an image for a Java application.

# We start from a base image that already has Java installed.
# openjdk:17-jdk-slim is a slim version of the OpenJDK 17 image.
FROM openjdk:17-jdk-slim

# We set the working directory inside the container to /ca4-part1/.
# All subsequent commands will be run from this directory.
WORKDIR /ca4-part1/

# We copy the built JAR file from our host machine to the container.
# The JAR file is located in the build/libs directory of the gradle_basic_demo project.
# It is named ca4-part1.jar inside the container.
COPY ./gradle_basic_demo/build/libs/*.jar ca4-part1.jar

# We expose port 59001 in the container.
# This is the port that our application will be accessible on.
EXPOSE 59001

# We define the command that will be run when the container is started.
# The application is started with the java command, using the -cp option to specify the classpath.
# The main class of the application is basic_demo.ChatServerApp and it listens on port 59001.
ENTRYPOINT ["java", "-cp", "ca4-part1.jar", "basic_demo.ChatServerApp", "59001"]