# This Dockerfile_web is used to build and run a Java application using Gradle.

# We start from a base image that includes Gradle and JDK 17.
FROM gradle:jdk17 AS builder

# Metadata indicating the authors of the image.
LABEL authors="Andre Ferreira"

# Set the working directory in the Docker image filesystem.
WORKDIR /ca4-part1/

# Clone the Gradle Basic Demo project from Bitbucket.
RUN git clone https://bitbucket.org/pssmatos/gradle_basic_demo.git

# Change the working directory to the cloned project directory.
WORKDIR /ca4-part1/gradle_basic_demo

# Make the Gradle wrapper executable and run the 'clean build' task.
# This will clean the project, compile the code, and package it into a JAR file.
RUN chmod +x gradlew && ./gradlew clean build

# Expose port 59001 in the Docker container.
# This is the port that our application will be accessible on.
EXPOSE 59001

# The command that will be run when the Docker container starts.
# It starts the Java application and the Gradle server.
CMD ["sh", "-c", "java -jar build/libs/*.jar & gradle runServer"]